### ISSUE TITLE
运行 python test.py 报错

### ISSUE THREAD

**Issue by fortarch** [linyiLYi/street-fighter-ai#13]
![1681655023057](https://user-images.githubusercontent.com/108772386/232319571-5c057b94-e437-46e3-8406-bfd9c7ccce34.jpg)

**Comment by fortarch** [comment]
上述报错通过降级 protobuf ，升级 Numpy解决了。现在是新的错误。

2023-04-16 22:50:00.559332: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-04-16 22:50:00.572326: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
C:\ProgramData\Anaconda3\envs\StreetFighterAI\lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object observation_space. Consider using `custom_objects`
argument to replace this object.
Exception: __randomstate_ctor() takes from 0 to 1 positional arguments but 2 were given
  warnings.warn(
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    model = PPO.load(os.path.join(MODEL_DIR, MODEL_NAME), env=env)
  File "C:\ProgramData\Anaconda3\envs\StreetFighterAI\lib\site-packages\stable_baselines3\common\base_class.py", line 678, in load
    raise KeyError("The observation_space and action_space were not given, can't verify new environments")
KeyError: "The observation_space and action_space were not given, can't verify new environments"

**Comment by fortarch** [comment]
ppo_ryu_2000000_steps_updated.zip  要解压吗？

**Comment by awake2023** [comment]
不需要
