### ISSUE TITLE
在运行项目之后出现了一些问题

### ISSUE THREAD

**Issue by Fang0000420** [linyiLYi/street-fighter-ai#23]
`Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
Wrapping the env in a VecTransposeImage.

Fighting Begins!

Traceback (most recent call last):
  File "test.py", line 79, in <module>
    obs, reward, done, info = env.step(action)
  File "D:\Last\street-fighter-ai\main\street_fighter_custom_wrapper.py", line 83, in step
    curr_player_health = info['agent_hp']
KeyError: 'agent_hp'`

昨天使用cmd运行成功了 今天想在vscode启动 在输入命令python test.py后报出这个错误

**Comment by littlePrettySoup** [comment]
可能是retro的版本不匹配导致的。把test.py和street_fighter_custom_wrapper.py两个文件里的 'agnet_hp"换成'health',  'enemy_hp'换成'enemy_health' 就可以运行了
