### ISSUE TITLE
按照README.MD文件描述步骤进行了，可是还是卡在了运行的最后一步，找了很多方法，依然不行。

### ISSUE THREAD

**Issue by 1evykim** [linyiLYi/street-fighter-ai#40]
C:\Users\my\.conda\envs\StreetFighterAI\lib\site-packages\stable_baselines3\common\save_util.py:166: UserWarning: Could not deserialize object observation_space. Consider using `custom_objects` argument to replace this object.
Exception: __randomstate_ctor() takes from 0 to 1 positional arguments but 2 were given
  warnings.warn(
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    model = PPO.load(os.path.join(MODEL_DIR, MODEL_NAME), env=env)
  File "C:\Users\my\.conda\envs\StreetFighterAI\lib\site-packages\stable_baselines3\common\base_class.py", line 678, in load
    raise KeyError("The observation_space and action_space were not given, can't verify new environments")
KeyError: "The observation_space and action_space were not given, can't verify new environments"
以上是报错信息，有大佬可以解答问题在哪里吗？谢谢！

**Comment by wuzhendong123** [comment]
我也碰到这类问题

**Comment by wuzhendong123** [comment]
也卡在这了
