### ISSUE TITLE
林哥，运行出错TypeError: filename must be a str or bytes object, or a file

### ISSUE THREAD

**Issue by Datou** [linyiLYi/street-fighter-ai#5]
(.venv) F:\street-fighter-ai\main>python test.py
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    env = make_env(game, state="Champion.Level12.RyuVsBison")()
  File "test.py", line 38, in _init
    env = retro.make(
  File "F:\street-fighter-ai\main\.venv\lib\site-packages\retro\__init__.py", line 55, in make
    return RetroEnv(game, state, inttype=inttype, **kwargs)
  File "F:\street-fighter-ai\main\.venv\lib\site-packages\retro\retro_env.py", line 60, in __init__
    self.load_state(self.statename, inttype)
  File "F:\street-fighter-ai\main\.venv\lib\site-packages\retro\retro_env.py", line 271, in load_state
    with gzip.open(retro.data.get_file_path(self.gamename, statename, inttype), 'rb') as fh:
  File "C:\Users\Datou\AppData\Local\Programs\Python\Python38\lib\gzip.py", line 62, in open
    raise TypeError("filename must be a str or bytes object, or a file")
TypeError: filename must be a str or bytes object, or a file

ROM文件已经放好了
![image](https://user-images.githubusercontent.com/15013/232261966-f67b4336-2dad-463a-b25b-8ca1aa728640.png)

**Comment by Datou** [comment]
是我自己漏掉了一步文件覆盖，问题已经解决，可以运行了
![image](https://user-images.githubusercontent.com/15013/232262046-8d545ca7-6e0e-4d9f-8ed7-6cf964a9644c.png)

**Comment by linyiLYi** [comment]
好的，目前 test.py 默认调用的是第 2500000 步的模型参数，改成七百万就可以看到视频里的效果。脚本里的其它参数也可以玩一玩，比如 RESET 设成 False 就不会只重复这一局了，而是会继续向下打

**Comment by Datou** [comment]
感谢林哥的回复。RESET 设成 False 确实好使，但AI能力有限，输多赢少。
