### ISSUE TITLE
在执行python test.py时报错，有无大佬看一下啥问题

### ISSUE THREAD

**Issue by wangxun6** [linyiLYi/street-fighter-ai#68]
Traceback (most recent call last):
  File "C:\Users\dell\.conda\envs\StreetFighterAI\lib\site-packages\retro\__init__.py", line 49, in make
    retro.data.get_romfile_path(game, inttype)
  File "C:\Users\dell\.conda\envs\StreetFighterAI\lib\site-packages\retro\data\__init__.py", line 288, in get_romfile_path
    raise FileNotFoundError("No romfiles found for game: %s" % game)
FileNotFoundError: No romfiles found for game: StreetFighterIISpecialChampionEdition-Genesis

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 49, in <module>
    env = make_env(game, state="Champion.Level12.RyuVsBison")()
  File "test.py", line 38, in _init
    env = retro.make(
  File "C:\Users\dell\.conda\envs\StreetFighterAI\lib\site-packages\retro\__init__.py", line 54, in make
    raise FileNotFoundError('Game not found: %s. Did you make sure to import the ROM?' % game)
FileNotFoundError: Game not found: StreetFighterIISpecialChampionEdition-Genesis. Did you make sure to import the ROM?

**Comment by JizhiXiang** [comment]
你这是没有下载游戏附件rom.md。
